/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicle.demo;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JWindow;

/**
 *
 * @author 2015_SE_101 and 2015_SE_092
 */

class spl  extends JWindow   {
  private int duration;
  public spl(int d) {
    duration = d;
  }

public void showSplash() {
    JPanel content = (JPanel)getContentPane();
    content.setBackground(Color.white);

    // Set the window's bounds, centering the window
    int width = 535;
    int height =530;
    Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (screen.width-width)/2;
    int y = (screen.height-height)/2;
    setBounds(x,y,width,height);

    // Build the splash screen
    JLabel label = new JLabel(new ImageIcon("C:\\Users\\One Click\\Desktop\\vehicle demo\\src\\vehicle\\demo\\splash.jpg"));
    JLabel copyrt = new JLabel
      ("Copyright @ Vehicle Management System", JLabel.CENTER);
    copyrt.setFont(new Font("Sans-Serif", Font.BOLD, 12));
    content.add(label, BorderLayout.CENTER);
    content.add(copyrt, BorderLayout.SOUTH);
    Color oraRed = new Color(156, 20, 20,  255);
    content.setBorder(BorderFactory.createLineBorder(oraRed, 10));

    // Display it
    setVisible(true);

    // Wait a little while, maybe while loading resources
    try { Thread.sleep(duration); } catch (Exception e) {}

    setVisible(false);
  }

  public void showSplashAndExit() {
    showSplash();
    //System.exit(0);
  }
}




public class VJFrame extends javax.swing.JFrame {

    /**
     * Creates new form VJFrame
     */
    
    protected Object curr_values[] = new Object[9];
protected ResultSet rs;
protected vh_db db_proc;
DefaultListModel lm = new DefaultListModel();
    
    public VJFrame() {
         try{ 
           initComponents();
        db_proc =  new vh_db();
          show_values();
    }
       catch(SQLException e){
      JOptionPane.showMessageDialog(null,e);
      
       }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    //start  get button
     public String get_s(Object x_ob) {
          if(x_ob == null)
              return "";
          else 
              return String.valueOf(x_ob);
          
      }
    
    
     void show_values() {
       id.setText(get_s(curr_values[1]));
       
        vt.setText(get_s(curr_values[2]));
       brand.setText(get_s(curr_values[3]));
       doors.setText(get_s(curr_values[4]));
       wheels.setText(get_s(curr_values[5]));
        seats.setText(get_s(curr_values[6]));
         mspeed.setText(get_s(curr_values[7]));
          co.setText(get_s(curr_values[8]));
       
       
    }
    
    
     public void search_values() {
      try {
          int i = Integer.parseInt(id.getText());
        rs = db_proc.load_data(i);
        System.out.println("***");
        if (rs.next()) {
           curr_values[1] = rs.getInt("id");
           curr_values[2] = rs.getInt("vtype");
           curr_values[3] = rs.getString("make");
           curr_values[4] = rs.getInt("doors");
           curr_values[5] = rs.getInt("wheels");
           curr_values[6] = rs.getInt("seats");
           curr_values[7] = rs.getInt("mspeed");
           curr_values[8] = rs.getBoolean("control");
            
            rs.close();
        }
       show_values(); 
        
      }
      catch(SQLException e) {
         JOptionPane.showMessageDialog(null,e);
      }
      
    
  }
    
   //end of get button 
    
     
     //start of save button
    
     public int save_values() throws SQLException {
            
      set_values();
      return db_proc.db_save(get_value(1), get_value(2), 
                                    get_value(3), get_value(4) , get_value(5), get_value(6) ,get_value(7) ,get_value(8) ); 
      
    }
     
      public Object get_value(int x_col) {
      return curr_values[x_col];
           
    }
      
       public void set_values() {
      int x_col;
      
      set_value(1,get_id_shown());
      set_value(2,get_vtype());
      set_value(3,get_brand());
      set_value(4,get_doors());
      set_value(5,get_wheels());
      set_value(6,get_seats());
      set_value(7,get_mspeed());    
      set_value(8,get_control());
      
    }
       
       public void set_value(int x_col, Object x_value) {
      curr_values[x_col] = x_value;
           
    }
       
        public Object get_id_shown() {
      return get_values_shown()[1];
      
    }
         
          public Object get_vtype() {
      return get_values_shown()[2];
      
    }
          
           public Object get_brand() {
      return get_values_shown()[3];
      
    }
            public Object get_doors() {
      return get_values_shown()[4];
      
    }
           public Object get_wheels() {
      return get_values_shown()[5];
      
    }
           
            public Object get_seats() {
      return get_values_shown()[6];
      
    }
           public Object get_mspeed() {
      return get_values_shown()[7];
      
    }
       public Object get_control() {
      return get_values_shown()[8];
      
    }
      
       public Object[] get_values_shown() {
      int x_col;
      Object x_values[] = new Object[9];
      
      x_values[1] = Integer.parseInt(id.getText());
      x_values[2] = Integer.parseInt(vt.getText());
      x_values[3] = brand.getText();
       x_values[4] = Integer.parseInt(doors.getText());
        x_values[5] = Integer.parseInt(wheels.getText());
         x_values[6] = Integer.parseInt(seats.getText());
          x_values[7] = Integer.parseInt(mspeed.getText());
           x_values[8] = Boolean.parseBoolean(co.getText());
     
      
      return x_values;
    }
         
    //end of save button
       
       //start of get ids button
       public void fill_listbox() throws SQLException{
         DefaultListModel lm = new DefaultListModel();
         getids.setModel(lm);
         rs = db_proc.get_jlist();
         while(rs.next()){
        String id = rs.getString("id");
        lm.addElement(id);
         
                 }
         }
        
       //end of get ids button
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        new_button = new javax.swing.JButton();
        insert_button = new javax.swing.JButton();
        get_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        vt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vtype = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        doors = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        wheels = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        seats = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mspeed = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pc_cbox = new javax.swing.JCheckBox();
        nc_cbox = new javax.swing.JCheckBox();
        co = new javax.swing.JTextField();
        save_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        getids_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        getids = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(49, 36, 36));
        setLocation(new java.awt.Point(360, 90));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 62, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicle/demo/download.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 11, 203, 125));

        new_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicle/demo/button_new (4).jpg"))); // NOI18N
        new_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        new_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        new_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(new_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 125, 45));

        insert_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicle/demo/button_insert.jpg"))); // NOI18N
        insert_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        insert_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(insert_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 124, 41));

        get_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicle/demo/button_get.jpg"))); // NOI18N
        get_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        get_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        get_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(get_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, 40));

        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicle/demo/button_exit.jpg"))); // NOI18N
        exit_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 120, 40));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Copyright @ Vehicle Management System");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel4.setText(" ID :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, -1));

        id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 130, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel5.setText("Vehicle Type : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));
        jPanel2.add(vt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 30, -1));

        vtype.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "0 : Truck", "1 : Bus", "2 : Crane", "3 : Bulldozer", "4 : Jeep", "5: Car" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vt, org.jdesktop.beansbinding.ObjectProperty.create(), vtype, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        vtype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vtypeMouseClicked(evt);
            }
        });
        vtype.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vtypeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(vtype);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 80, 70));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel6.setText(" Brand :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel2.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel7.setText("Doors : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));
        jPanel2.add(doors, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 150, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel8.setText("Wheels :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel2.add(wheels, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 100, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel9.setText("Seats  :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));
        jPanel2.add(seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 150, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel10.setText("Maximum Speed :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel2.add(mspeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 230, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel11.setText("Control : ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        pc_cbox.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        pc_cbox.setText("Power Control");
        pc_cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc_cboxActionPerformed(evt);
            }
        });
        jPanel2.add(pc_cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 120, -1));

        nc_cbox.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        nc_cbox.setText("Normal Control");
        nc_cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nc_cboxActionPerformed(evt);
            }
        });
        jPanel2.add(nc_cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 130, -1));
        jPanel2.add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 90, 30));

        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicle/demo/button_save.jpg"))); // NOI18N
        save_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 110, 40));

        jPanel3.setBackground(new java.awt.Color(71, 59, 59));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehicle Management System");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 380, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 16)); // NOI18N
        jLabel12.setText("Get Vechile ID List : ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        getids_button.setBackground(new java.awt.Color(51, 51, 51));
        getids_button.setForeground(new java.awt.Color(255, 255, 255));
        getids_button.setText("Get ID");
        getids_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getids_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getids_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(getids_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        getids.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ids comes here" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(getids);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 80, 70));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 430, 10));

        jLabel14.setText("RN/092-101");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 80, 20));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicle/demo/bg1.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 560));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 440, 550));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_buttonActionPerformed
        // TODO add your handling code here:
        //all text boxbecomes null
          id.setText("");
        brand.setText("");
         doors.setText("");
          wheels.setText("");
          seats.setText("");
          mspeed.setText("");
          co.setText("");
          vt.setText("");
          getids.setModel(lm);
          lm.addElement("");
         
    }//GEN-LAST:event_new_buttonActionPerformed

    private void insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_buttonActionPerformed
        // TODO add your handling code here:
        int x_count;
      //  Object x_new_id = get_input_id();
      
        Object x_new_id = Integer.parseInt(id.getText());
         Object x_new_vtype = Integer.parseInt(vt.getText());
          Object x_new_make = brand.getText();
           Object x_new_doors = Integer.parseInt(doors.getText());
            Object x_new_wheels = Integer.parseInt(wheels.getText());
            Object x_new_seats = Integer.parseInt(seats.getText());
             Object x_new_mspeed = Integer.parseInt(mspeed.getText());
              Object x_new_control = Boolean.parseBoolean(co.getText());
            
        
        Object x_inputs[] = {x_new_id, x_new_vtype, x_new_make, x_new_doors, x_new_wheels, x_new_seats, x_new_mspeed, x_new_control};
        try {
            x_count = db_proc.db_insert(x_new_id ,x_new_vtype , x_new_make , x_new_doors , x_new_wheels , x_new_seats ,x_new_mspeed ,x_new_control);
            if (x_count < 1) {
                  JOptionPane.showMessageDialog(null,"Record was not inserted");
                    return;
            }
            
            JOptionPane.showMessageDialog(null ,"Record is inserted sucessfully");
           id.setText("");
        brand.setText("");
         doors.setText("");
          wheels.setText("");
          seats.setText("");
          mspeed.setText("");
          co.setText("");
          vt.setText("");
           
        }
        catch(Exception e) {
           JOptionPane.showMessageDialog(null,"ERROR MESSAGE: " + e);
        }
         
        
    }//GEN-LAST:event_insert_buttonActionPerformed

    private void pc_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc_cboxActionPerformed
        // TODO add your handling code here:
         co.setText("True");
    }//GEN-LAST:event_pc_cboxActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        try {
            dispose();
            System.out.println("************************");
            System.out.println("Bye have a nice day");
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR: " + e);
        }
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        // TODO add your handling code here:
        
         int x_count;
        try {
                x_count = save_values();
                if (x_count < 1) 
                    JOptionPane.showMessageDialog(null,"Record was not saved");
            }
        catch(Exception e) {
          JOptionPane.showMessageDialog(null,"ERROR: " + e);
        }
        
    }//GEN-LAST:event_save_buttonActionPerformed

    private void get_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_buttonActionPerformed
        // TODO add your handling code here:
          search_values();
    }//GEN-LAST:event_get_buttonActionPerformed

    private void getids_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getids_buttonActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:

            fill_listbox();
        } 
         catch (SQLException ex) {
            Logger.getLogger(VJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_getids_buttonActionPerformed

    private void vtypeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vtypeValueChanged
        // TODO add your handling code here:
         int i = vtype.getSelectedIndex();
     vt.setText(Integer.toString(i));
    }//GEN-LAST:event_vtypeValueChanged

    private void vtypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtypeMouseClicked
        // TODO add your handling code here:
         int i = vtype.getSelectedIndex();
     vt.setText(Integer.toString(i));
    }//GEN-LAST:event_vtypeMouseClicked

    private void nc_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nc_cboxActionPerformed
        // TODO add your handling code here:
         co.setText("False");
    }//GEN-LAST:event_nc_cboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        spl splash = new spl(5000);
    // Normally, we'd call splash.showSplash() and get on with the program.
    // But, since this is only a test...
    splash.showSplashAndExit(); 
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brand;
    private javax.swing.JTextField co;
    private javax.swing.JTextField doors;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton get_button;
    private javax.swing.JList<String> getids;
    private javax.swing.JButton getids_button;
    private javax.swing.JTextField id;
    private javax.swing.JButton insert_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField mspeed;
    private javax.swing.JCheckBox nc_cbox;
    private javax.swing.JButton new_button;
    private javax.swing.JCheckBox pc_cbox;
    private javax.swing.JButton save_button;
    private javax.swing.JTextField seats;
    private javax.swing.JTextField vt;
    private javax.swing.JList<String> vtype;
    private javax.swing.JTextField wheels;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
